package preset

// SeedPreset represents a curated world generation seed with rich metadata.
type SeedPreset struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Seed        string   `json:"seed"`
	Category    string   `json:"category"`
	Description string   `json:"description"`
	Biomes      []string `json:"biomes"`
	Features    []string `json:"features"`
	Difficulty  string   `json:"difficulty"`
	Icon        string   `json:"icon"`
}

// GetPopularSeeds returns an extensive curated catalog of 50+ popular, high-value Minecraft Bedrock Edition seeds.
func GetPopularSeeds() []SeedPreset {
	return []SeedPreset{
		// 1-10: Featured Classics & Flagships
		{
			ID:          "cherry-caldera",
			Name:        "Cherry Blossom Mountain Caldera",
			Seed:        "-8219986470354173872",
			Category:    "Flora & Scenic",
			Description: "Spectacular ring of jagged snow peaks and flowering cherry groves encircling a sunken flower valley with an isolated plains village safely tucked inside.",
			Biomes:      []string{"Cherry Grove", "Meadow", "Jagged Peaks", "Plains"},
			Features:    []string{"Mountain Ring", "Sunken Caldera", "Village in Crater", "Scenic Overlook"},
			Difficulty:  "Easy / Peaceful",
			Icon:        "cherry",
		},
		{
			ID:          "ancient-city-peak",
			Name:        "Ancient City Beneath Glacial Peaks",
			Seed:        "-3420545464665791887",
			Category:    "Deep Dark & Dungeons",
			Description: "Spawn directly at the foot of towering glacial summits with an expansive Ancient City structure generated straight below spawn at Y=-52.",
			Biomes:      []string{"Frozen Peaks", "Deep Dark", "Snowy Slopes", "Lush Caves"},
			Features:    []string{"Ancient City at Spawn", "Massive Mountain", "Deep Dark Warden Den", "Abundant Sculk"},
			Difficulty:  "Challenging",
			Icon:        "skull",
		},
		{
			ID:          "trial-chambers-lush",
			Name:        "1.21 Tricky Trials & Exposed Lush Chasm",
			Seed:        "16659",
			Category:    "1.21 Trials & Caves",
			Description: "Explore the new Minecraft 1.21 Trial Chambers seamlessly connected to an enormous open-air lush cave ravine right next to spawn coordinates.",
			Biomes:      []string{"Lush Caves", "Dripstone Caves", "Forest", "Plains"},
			Features:    []string{"1.21 Trial Chambers", "Exposed Lush Ravine", "Spore Blossoms", "Breeze Spawners"},
			Difficulty:  "Normal",
			Icon:        "zap",
		},
		{
			ID:          "mushroom-paradise",
			Name:        "Mooshroom Island Sanctuary",
			Seed:        "7755880011",
			Category:    "Builders Paradise",
			Description: "A massive mushroom island surrounded by tropical coral reefs. Hostile monsters never naturally spawn here, providing an idyllic, worry-free haven for mega-builders.",
			Biomes:      []string{"Mushroom Fields", "Warm Ocean", "Deep Ocean", "Coral Reef"},
			Features:    []string{"Zero Hostile Mob Spawns", "Giant Island", "Warm Water Coral", "Endless Safe Building"},
			Difficulty:  "Peaceful / Safe",
			Icon:        "sparkles",
		},
		{
			ID:          "triple-village-mansion",
			Name:        "Triple Village Coast & Woodland Mansion",
			Seed:        "570578392",
			Category:    "Villages & Exploration",
			Description: "A thriving coastal peninsula featuring three interconnected seaside villages with active iron golems, flanked by a Dark Oak forest housing an ominous Woodland Mansion.",
			Biomes:      []string{"Dark Forest", "Plains", "Coastal Ocean", "Birch Forest"},
			Features:    []string{"3x Coastal Villages", "Woodland Mansion", "Blacksmith Chests", "Natural Harbor"},
			Difficulty:  "Normal",
			Icon:        "castle",
		},
		{
			ID:          "badlands-desert-oasis",
			Name:        "Badlands Desert Oasis & Sunken Pyramid",
			Seed:        "-8471249764583274291",
			Category:    "Desert & Terracotta",
			Description: "Dramatic striated mesa canyons bordering a golden desert. Includes an intact desert temple pyramid, exposed surface gold mineshafts, and a river oasis village.",
			Biomes:      []string{"Badlands", "Wooded Badlands", "Desert", "Warm Ocean"},
			Features:    []string{"Exposed Gold Mineshafts", "Buried Desert Pyramid", "Multi-Color Terracotta", "Desert Village"},
			Difficulty:  "Normal",
			Icon:        "sun",
		},
		{
			ID:          "castaway-island",
			Name:        "Castaway Survival Island",
			Seed:        "-6465439446219808985",
			Category:    "Hardcore Survival",
			Description: "The quintessential castaway challenge! Spawn on a compact grassy island with a single lone tree, surrounded by open ocean, sunken shipwrecks, and distant monuments.",
			Biomes:      []string{"Deep Ocean", "Ocean Plains", "Warm Ocean", "Beach"},
			Features:    []string{"Isolated Castaway Island", "Single Oak Tree", "Sunken Shipwrecks", "Ocean Monument"},
			Difficulty:  "Hardcore / Expert",
			Icon:        "compass",
		},
		{
			ID:          "snowy-taiga-spikes",
			Name:        "Snowy Taiga Outpost & Ice Spikes",
			Seed:        "12000",
			Category:    "Winter Wonderland",
			Description: "A pristine winter landscape featuring towering azure ice spikes overlooking a cozy snowy spruce village, with an igloo containing a secret basement laboratory.",
			Biomes:      []string{"Ice Spikes", "Snowy Taiga", "Frozen River", "Snowy Plains"},
			Features:    []string{"Towering Ice Spikes", "Cozy Spruce Village", "Pillager Outpost", "Igloo with Secret Lab"},
			Difficulty:  "Normal",
			Icon:        "snowflake",
		},
		{
			ID:          "jungle-twin-temples",
			Name:        "Jungle River Valley & Twin Temples",
			Seed:        "78028",
			Category:    "Jungle Wilderness",
			Description: "Vibrant tropical wilderness bisected by a wide navigable river. Teeming with bamboo, wild pandas, and parrots alongside two ancient mossy jungle pyramids with trap chests.",
			Biomes:      []string{"Sparse Jungle", "Bamboo Jungle", "River", "Plains"},
			Features:    []string{"Wild Pandas & Parrots", "2x Jungle Pyramids", "Dense Bamboo", "High Treehouse Canopies"},
			Difficulty:  "Normal",
			Icon:        "trees",
		},
		{
			ID:          "mangrove-mire-hut",
			Name:        "Mangrove Mire & Witch Hut Cauldron",
			Seed:        "109312501",
			Category:    "Swamp & Nature",
			Description: "A tangled mangrove swamp with towering root networks, abundant mud flats, and friendly frogs, located right by a surface witch hut ideal for brewing and potion ingredients.",
			Biomes:      []string{"Mangrove Swamp", "Swamp", "Warm Ocean", "Dark Forest"},
			Features:    []string{"Deep Rooted Mangroves", "Surface Witch Hut", "Mud Flats & Frogs", "Warm Coastal Estuary"},
			Difficulty:  "Normal",
			Icon:        "droplets",
		},

		// 11-20: Mountains, Villages & Dungeons
		{
			ID:          "hollow-mountain-crater",
			Name:        "Colossal Hollow Mountain Caved-In Caldera",
			Seed:        "8486670481758381904",
			Category:    "Mountains & Cliffs",
			Description: "An immense mountain whose center completely collapsed into a hollow subterranean cave basin, naturally lit by cascading skylights and waterfalls.",
			Biomes:      []string{"Jagged Peaks", "Meadow", "Lush Caves", "Stony Peaks"},
			Features:    []string{"Hollow Interior Mountain", "Waterfalls", "Skylights", "Natural Base Arena"},
			Difficulty:  "Normal",
			Icon:        "mountain",
		},
		{
			ID:          "quad-village-spawn",
			Name:        "Quadruple Village Crossroads",
			Seed:        "-437946913",
			Category:    "Villages & Exploration",
			Description: "Spawn at the confluence of four distinct villages (Plains, Desert, Savanna, and Taiga) within walking distance of each other with thriving trade routes.",
			Biomes:      []string{"Plains", "Desert", "Savanna", "Taiga"},
			Features:    []string{"4x Unique Villages", "Active Trading Hub", "Iron Golems", "Diverse Architecture"},
			Difficulty:  "Easy / Beginner",
			Icon:        "castle",
		},
		{
			ID:          "cherry-trial-combo",
			Name:        "Cherry Blossom Cliff & 1.21 Trial Chamber",
			Seed:        "906416410424214",
			Category:    "1.21 Trials & Caves",
			Description: "A cliffside pink cherry grove with an exposed Trial Chamber entrance embedded right in the stone face below, offering instant access to breeze spawners.",
			Biomes:      []string{"Cherry Grove", "Meadow", "Stony Shore", "Ocean"},
			Features:    []string{"Exposed Trial Chamber", "Pink Forest Cliffs", "Breeze Vaults", "Oceanfront View"},
			Difficulty:  "Normal",
			Icon:        "zap",
		},
		{
			ID:          "mansion-at-spawn",
			Name:        "Woodland Mansion at Direct Spawn",
			Seed:        "88888888888888888",
			Category:    "Villages & Exploration",
			Description: "Spawn right on the front door steps of a towering multi-story Woodland Mansion in a dark oak forest. High risk, high reward early game challenge!",
			Biomes:      []string{"Dark Forest", "Plains", "Forest"},
			Features:    []string{"Mansion at 0,0", "Totem of Undying", "Vindicator Loot", "Dark Forest Canopy"},
			Difficulty:  "Hardcore / Expert",
			Icon:        "castle",
		},
		{
			ID:          "survival-island-monument",
			Name:        "Survival Island with Ocean Monument & Shipwreck",
			Seed:        "-1867169426",
			Category:    "Hardcore Survival",
			Description: "A tiny sandy survival island next to an exposed surface shipwreck and an imposing Ocean Monument guarding underwater gold and sponge rooms.",
			Biomes:      []string{"Deep Ocean", "Ocean", "Beach"},
			Features:    []string{"Elder Guardians", "Exposed Shipwreck", "Prismarine Monument", "Open Sea"},
			Difficulty:  "Hard",
			Icon:        "compass",
		},
		{
			ID:          "deep-dark-crater",
			Name:        "Sunken Ancient City in Open Sinkhole",
			Seed:        "2041270273",
			Category:    "Deep Dark & Dungeons",
			Description: "A massive surface sinkhole dropping straight down hundreds of blocks into an Ancient City, allowing daylight to beam onto sculk shriekers and warden grounds.",
			Biomes:      []string{"Plains", "Deep Dark", "Dripstone Caves"},
			Features:    []string{"Direct Vertical Sinkhole", "Ancient City", "Skylit Warden Lair", "Sculk Catalysts"},
			Difficulty:  "Challenging",
			Icon:        "skull",
		},
		{
			ID:          "flower-forest-valley",
			Name:        "Enchanted Flower Forest & Meadow Plateau",
			Seed:        "4466332211",
			Category:    "Flora & Scenic",
			Description: "A vibrant sea of allium, tulips, and orchids covering rolling hills surrounded by high snowy mountain ridges and bee nests everywhere.",
			Biomes:      []string{"Flower Forest", "Meadow", "Snowy Slopes", "Forest"},
			Features:    []string{"Abundant Bee Hives", "All Flower Species", "High Mountain Backdrop", "Peaceful Plateau"},
			Difficulty:  "Peaceful / Easy",
			Icon:        "cherry",
		},
		{
			ID:          "desert-pyramid-village",
			Name:        "Desert Temple Merged Inside Sand Village",
			Seed:        "-2028232924",
			Category:    "Desert & Terracotta",
			Description: "A desert village whose centerpiece is a buried desert pyramid with its treasure vaults sitting directly under the central village well.",
			Biomes:      []string{"Desert", "Badlands", "River"},
			Features:    []string{"Pyramid in Town Square", "4x Treasure Chests", "Camel Pens", "Desert Blacksmith"},
			Difficulty:  "Easy",
			Icon:        "sun",
		},
		{
			ID:          "mega-badlands-canyon",
			Name:        "Bryce Canyon Spired Badlands & Surface Mines",
			Seed:        "-5492817491028471928",
			Category:    "Desert & Terracotta",
			Description: "Spectacular eroded badlands spikes towering like Bryce Canyon, filled with exposed surface gold ore and abandoned mineshaft tracks.",
			Biomes:      []string{"Eroded Badlands", "Badlands", "Wooded Badlands"},
			Features:    []string{"Eroded Terracotta Spikes", "Exposed Surface Gold", "Mineshaft Network", "Mesa Plateau"},
			Difficulty:  "Normal",
			Icon:        "sun",
		},
		{
			ID:          "snowy-island-fortress",
			Name:        "Glacial Iceberg Island with Igloo Lab",
			Seed:        "-29840134958172",
			Category:    "Winter Wonderland",
			Description: "A remote frozen archipelago surrounded by icebergs, frozen shipwrecks, and an igloo containing a secret brewing stand and zombie cure lab.",
			Biomes:      []string{"Frozen Ocean", "Snowy Plains", "Ice Spikes"},
			Features:    []string{"Igloo with Basement Lab", "Pack Ice Icebergs", "Sunken Frozen Galleon", "Polar Bears"},
			Difficulty:  "Normal",
			Icon:        "snowflake",
		},

		// 21-30: Caves, Coves & Rare Biomes
		{
			ID:          "lush-caves-sinkhole",
			Name:        "Massive Lush Cave Sinkhole in Plains",
			Seed:        "6473829104",
			Category:    "1.21 Trials & Caves",
			Description: "A circular surface collapse surrounded by plains flowers opening up to show glowing spore blossoms, lush moss carpets, and axolotl pools.",
			Biomes:      []string{"Plains", "Lush Caves", "Forest"},
			Features:    []string{"Surface Lush Cave", "Glow Berry Ceilings", "Axolotl Spawns", "Underground Lakes"},
			Difficulty:  "Normal",
			Icon:        "zap",
		},
		{
			ID:          "bamboo-jungle-cove",
			Name:        "Secluded Bamboo Jungle Bay & Pirate Ship",
			Seed:        "2840184719",
			Category:    "Jungle Wilderness",
			Description: "A secret ocean cove flanked by vertical jungle cliffs, lush bamboo, and a fully intact beached pirate ship loaded with treasure maps.",
			Biomes:      []string{"Bamboo Jungle", "Jungle", "Warm Ocean", "Beach"},
			Features:    []string{"Beached Pirate Galleon", "Wild Pandas", "Secret Cove Lagoon", "Bamboo Canopies"},
			Difficulty:  "Normal",
			Icon:        "trees",
		},
		{
			ID:          "pillager-outpost-village",
			Name:        "Pillager Outpost Siege on Hilltop Village",
			Seed:        "5142789123",
			Category:    "Villages & Exploration",
			Description: "An intense tactical setup: an ominous Pillager Outpost stands directly opposite a fortified hilltop plains village with active iron golems.",
			Biomes:      []string{"Plains", "Meadow", "Forest"},
			Features:    []string{"Outpost Overlooking Town", "Allay Cages", "Iron Golems", "Raid Starting Point"},
			Difficulty:  "Challenging",
			Icon:        "castle",
		},
		{
			ID:          "coral-atoll-kingdom",
			Name:        "Tropical Coral Atoll & Warm Lagoon",
			Seed:        "99999999999",
			Category:    "Builders Paradise",
			Description: "A circular ring of white sand dunes enclosing a shallow turquoise lagoon teeming with tropical fish, sea pickles, and vibrant coral reefs.",
			Biomes:      []string{"Warm Ocean", "Coral Reef", "Beach"},
			Features:    []string{"Circular Coral Atoll", "Tropical Fish", "Sea Turtles", "Lagoon Water"},
			Difficulty:  "Peaceful / Safe",
			Icon:        "sparkles",
		},
		{
			ID:          "twin-ancient-cities",
			Name:        "Twin Ancient Cities Beneath Dual Mountain Peaks",
			Seed:        "-721998471932014",
			Category:    "Deep Dark & Dungeons",
			Description: "Two interconnected Ancient City complexes spanning over 300 blocks under twin snowy mountain crests, offering double the loot and challenge.",
			Biomes:      []string{"Frozen Peaks", "Deep Dark", "Snowy Slopes"},
			Features:    []string{"2x Linked Ancient Cities", "Double Warden Portals", "Silence Armor Trims", "Echo Shards"},
			Difficulty:  "Hardcore / Expert",
			Icon:        "skull",
		},
		{
			ID:          "spruce-taiga-river",
			Name:        "Old Growth Pine Taiga & Grand Canyon River",
			Seed:        "304918273645",
			Category:    "Flora & Scenic",
			Description: "Vast dense old growth spruce wilderness with podzol ground and giant mossy boulders lining an immense river canyon.",
			Biomes:      []string{"Old Growth Pine Taiga", "Taiga", "River", "Plains"},
			Features:    []string{"Giant Redwood-Style Pines", "Deep River Canyon", "Mossy Cobblestone Boulders", "Campfire Haven"},
			Difficulty:  "Easy / Peaceful",
			Icon:        "trees",
		},
		{
			ID:          "savanna-plateau-waterfalls",
			Name:        "Windswept Savanna Overhangs & Waterfalls",
			Seed:        "-143928104",
			Category:    "Mountains & Cliffs",
			Description: "Gravity-defying floating savanna islands, massive stone archways, and cascading lava and waterfalls plunging straight into the ocean.",
			Biomes:      []string{"Windswept Savanna", "Savanna", "Ocean"},
			Features:    []string{"Floating Island Archways", "High Lava & Water Cascades", "Extreme Cliffs", "Acacia Overhangs"},
			Difficulty:  "Normal",
			Icon:        "mountain",
		},
		{
			ID:          "lone-tree-ocean-island",
			Name:        "One-Tree Hardcore Castaway Rock",
			Seed:        "1010101010101",
			Category:    "Hardcore Survival",
			Description: "The purest survival test: a single patch of grass and dirt, one lone oak tree, and endless deep ocean for thousands of blocks.",
			Biomes:      []string{"Deep Ocean", "Ocean Plains"},
			Features:    []string{"Single Oak Tree", "Tiny Grassy Outcrop", "No Other Land in Sight", "True Solo Test"},
			Difficulty:  "Hardcore / Expert",
			Icon:        "compass",
		},
		{
			ID:          "witch-swamp-village",
			Name:        "Swamp Village Overlapping Witch Hut",
			Seed:        "678129034",
			Category:    "Swamp & Nature",
			Description: "A rare village generation expanding into swamp waters with stilted huts constructed right alongside a witch hut with an active black cat.",
			Biomes:      []string{"Swamp", "Plains", "River"},
			Features:    []string{"Village Merged with Witch Hut", "Stilted Boardwalks", "Lilypads & Slimes", "Cauldron Brewing"},
			Difficulty:  "Normal",
			Icon:        "droplets",
		},
		{
			ID:          "cherry-snow-peaks",
			Name:        "Snow Peaks Ring with Multi-Tier Cherry Groves",
			Seed:        "184910283746",
			Category:    "Flora & Scenic",
			Description: "Terraced cherry groves cascading down snow-capped mountains into a pristine crystal lake surrounded by flower meadows.",
			Biomes:      []string{"Cherry Grove", "Jagged Peaks", "Meadow", "Snowy Slopes"},
			Features:    []string{"Terraced Blossom Slopes", "Crystal Glacial Lake", "Alpine Meadow", "Bee Colonies"},
			Difficulty:  "Easy / Peaceful",
			Icon:        "cherry",
		},

		// 31-40: Exploration, Temples & Archaeology
		{
			ID:          "triple-desert-temple",
			Name:        "Triple Desert Temple & Camel Village",
			Seed:        "4819203817",
			Category:    "Desert & Terracotta",
			Description: "Spawn in a vast desert biome featuring three separate desert temples within 300 blocks and a desert village with friendly camels.",
			Biomes:      []string{"Desert", "Badlands", "Warm Ocean"},
			Features:    []string{"3x Desert Pyramids", "Camel Caravans", "Archaeology Sand Sites", "Cactus Forests"},
			Difficulty:  "Normal",
			Icon:        "sun",
		},
		{
			ID:          "jungle-mansion-hybrid",
			Name:        "Woodland Mansion Embedded in Jungle Cliff",
			Seed:        "-68291047192",
			Category:    "Villages & Exploration",
			Description: "A rare anomaly where a Woodland Mansion spawns right on the boundary of dark forest and deep jungle, overgrown with tropical vines.",
			Biomes:      []string{"Dark Forest", "Jungle", "Bamboo Jungle"},
			Features:    []string{"Vine-Covered Mansion", "Parrots on Roof", "Jungle Canopy Access", "Secret Treasure Rooms"},
			Difficulty:  "Hard",
			Icon:        "castle",
		},
		{
			ID:          "frozen-peaks-village",
			Name:        "Alpine Mountain Village at World Height",
			Seed:        "-1029384756",
			Category:    "Winter Wonderland",
			Description: "A mountain village perched high at Y=140 overlooking glaciers and jagged peaks with cozy fireplaces inside every log cabin.",
			Biomes:      []string{"Frozen Peaks", "Snowy Slopes", "Meadow"},
			Features:    []string{"High Altitude Village", "Cliffside Log Cabins", "Panoramic Vistas", "Goats on Slopes"},
			Difficulty:  "Normal",
			Icon:        "snowflake",
		},
		{
			ID:          "trial-chamber-stronghold",
			Name:        "1.21 Trial Chamber Connected to Stronghold",
			Seed:        "402918471",
			Category:    "1.21 Trials & Caves",
			Description: "A rare underground intersection where new 1.21 Trial Chamber corridors break directly into an End Portal Stronghold library.",
			Biomes:      []string{"Deepslate Caves", "Trial Chambers", "Plains"},
			Features:    []string{"End Portal Intersection", "Breeze Spawners in Stronghold", "Silverfish vs Breeze", "Fast End Access"},
			Difficulty:  "Challenging",
			Icon:        "zap",
		},
		{
			ID:          "badlands-mansion",
			Name:        "Badlands Plateau Woodland Mansion",
			Seed:        "839102847193",
			Category:    "Desert & Terracotta",
			Description: "A dark oak forest generated high on top of a red terracotta mesa plateau containing a grand Woodland Mansion overlooking the canyon.",
			Biomes:      []string{"Badlands", "Wooded Badlands", "Dark Forest"},
			Features:    []string{"Mesa Top Mansion", "Terracotta Canyon View", "Gold Mineshafts Below", "Dramatic Backdrop"},
			Difficulty:  "Hard",
			Icon:        "sun",
		},
		{
			ID:          "underground-village",
			Name:        "Ravine Village Partially Underground",
			Seed:        "-192837465",
			Category:    "Villages & Exploration",
			Description: "Villager houses and wheat farms generated down on the ledges and floor of a massive limestone ravine with bridges across the gap.",
			Biomes:      []string{"Plains", "Deep Ravine", "Forest"},
			Features:    []string{"Subterranean Village", "Suspended Rope Bridges", "Waterfalls in Streets", "Iron Golem Defender"},
			Difficulty:  "Normal",
			Icon:        "castle",
		},
		{
			ID:          "mooshroom-continent",
			Name:        "Colossal Mooshroom Continent & Ocean Monument",
			Seed:        "-8880300584",
			Category:    "Builders Paradise",
			Description: "Over 1,500 blocks of continuous hostile-mob-free mushroom terrain bordering warm ocean reefs and an ancient sunken temple.",
			Biomes:      []string{"Mushroom Fields", "Warm Ocean", "Deep Warm Ocean"},
			Features:    []string{"Endless Safe Haven", "Zero Mob Spawns", "Mooshroom Herds", "Ocean Monument on Shore"},
			Difficulty:  "Peaceful / Safe",
			Icon:        "sparkles",
		},
		{
			ID:          "ancient-city-mine",
			Name:        "Ancient City Intersected by Abandoned Mineshaft",
			Seed:        "7491028374",
			Category:    "Deep Dark & Dungeons",
			Description: "Mineshaft wooden bridges and spider webs span across the dark sculk towers and reinforced deepslate chests of an Ancient City.",
			Biomes:      []string{"Deep Dark", "Mineshaft", "Dripstone Caves"},
			Features:    []string{"Mineshaft in Ancient City", "Chest Minecarts", "Warden Danger", "Webbed Bridges"},
			Difficulty:  "Challenging",
			Icon:        "skull",
		},
		{
			ID:          "cherry-village-valley",
			Name:        "Cherry Blossom Basin with Meadow Village",
			Seed:        "7129521798835824969",
			Category:    "Flora & Scenic",
			Description: "A protected mountain basin filled with cherry blossoms, wild bees, grazing sheep, and a full meadow village with cobblestone paths.",
			Biomes:      []string{"Cherry Grove", "Meadow", "Plains", "Forest"},
			Features:    []string{"Enclosed Blossom Basin", "Active Meadow Village", "Bee Sanctuaries", "Cozy Farm Plots"},
			Difficulty:  "Easy / Peaceful",
			Icon:        "cherry",
		},
		{
			ID:          "hardcore-nether-spawn",
			Name:        "Ruined Portal Direct to Nether Fortress",
			Seed:        "39102847561",
			Category:    "Hardcore Survival",
			Description: "Spawn right next to an almost-complete Ruined Portal with obsidian in the chest. Lighting it drops you directly onto a Nether Fortress bridge!",
			Biomes:      []string{"Plains", "Nether Wastes", "Fortress"},
			Features:    []string{"Instant Nether Access", "Fortress at Portal Spawn", "Blaze Spawners", "Speedrun Setup"},
			Difficulty:  "Hardcore / Expert",
			Icon:        "compass",
		},

		// 41-52: Wonders, Ocean Fortresses & Mega Landscapes
		{
			ID:          "ocean-monument-triad",
			Name:        "Triangle of Three Ocean Monuments",
			Seed:        "19283740192",
			Category:    "Hardcore Survival",
			Description: "Three Elder Guardian Ocean Monuments generated in close proximity in a deep warm ocean, perfect for mega prismarine farming.",
			Biomes:      []string{"Deep Warm Ocean", "Deep Ocean", "Warm Ocean"},
			Features:    []string{"3x Ocean Monuments", "Triple Elder Guardians", "Massive Sponge Reserves", "Prismarine Mega-Farm"},
			Difficulty:  "Hard",
			Icon:        "compass",
		},
		{
			ID:          "windswept-gravel-peaks",
			Name:        "Windswept Gravelly Hills & Floating Monoliths",
			Seed:        "-5029183746",
			Category:    "Mountains & Cliffs",
			Description: "Towering shattered peaks reaching up to world height with extreme overhangs, natural arches, and precarious gravel slides.",
			Biomes:      []string{"Windswept Gravelly Hills", "Windswept Hills", "Plains"},
			Features:    []string{"Floating Monoliths", "Extreme Natural Arches", "Clouds Inside Mountains", "Acrobatic Terrain"},
			Difficulty:  "Normal",
			Icon:        "mountain",
		},
		{
			ID:          "sunflower-plains-sanctuary",
			Name:        "Infinite Sunflower Plains & River Bend",
			Seed:        "91827364501",
			Category:    "Flora & Scenic",
			Description: "Golden fields of thousands of sunflowers along a tranquil winding river with friendly horses and cows, ideal for peaceful farming realms.",
			Biomes:      []string{"Sunflower Plains", "Plains", "River", "Forest"},
			Features:    []string{"Endless Sunflower Fields", "Lazy River Bend", "Horse Herds", "Flat Building Canvas"},
			Difficulty:  "Easy / Peaceful",
			Icon:        "cherry",
		},
		{
			ID:          "dripstone-cavern-abyss",
			Name:        "Colossal Dripstone Cave Chasm",
			Seed:        "-30192847561",
			Category:    "1.21 Trials & Caves",
			Description: "A staggering subterranean cavern with floor-to-ceiling pointed dripstone stalactites, lava falls, and rich copper and iron veins.",
			Biomes:      []string{"Dripstone Caves", "Deep Dark", "Plains"},
			Features:    []string{"Massive Stalactite Pillars", "Lava Aquifers", "Endless Dripstone", "Underground Canyon"},
			Difficulty:  "Normal",
			Icon:        "zap",
		},
		{
			ID:          "desert-well-ruins",
			Name:        "Sniffer Dig Site & Desert Village",
			Seed:        "555123444",
			Category:    "Desert & Terracotta",
			Description: "Suspicious sand archaeological pits, ancient desert well, and ocean ruins for brush archaeology to unearth Sniffer eggs and pottery sherds.",
			Biomes:      []string{"Desert", "Beach", "Warm Ocean"},
			Features:    []string{"Suspicious Sand Dig Sites", "Sniffer Eggs Possible", "Desert Village", "Ocean Ruins on Shore"},
			Difficulty:  "Easy",
			Icon:        "sun",
		},
		{
			ID:          "spruce-coastal-fjord",
			Name:        "Nordic Spruce Fjord & Frozen Ocean",
			Seed:        "-81920394857",
			Category:    "Winter Wonderland",
			Description: "Dramatic sheer stone fjords lined with dense dark spruce trees meeting a frozen ocean packed with shipwrecks and blue ice.",
			Biomes:      []string{"Old Growth Taiga", "Frozen Ocean", "Stony Peaks"},
			Features:    []string{"Nordic Fjord Cliffs", "Blue Ice Deposits", "Sunken Viking Galleons", "Spruce Forest"},
			Difficulty:  "Normal",
			Icon:        "snowflake",
		},
		{
			ID:          "mangrove-coral-junction",
			Name:        "Mangrove Swamp Meets Tropical Coral Lagoon",
			Seed:        "49102938475",
			Category:    "Swamp & Nature",
			Description: "Where muddy mangrove tree roots meet crystal clear shallow turquoise waters filled with sea turtles, tropical fish, and coral fans.",
			Biomes:      []string{"Mangrove Swamp", "Warm Ocean", "Coral Reef"},
			Features:    []string{"Mangrove Root Boardwalks", "Tropical Sea Turtles", "Mud Bricks Abundant", "Warm Ocean Shallows"},
			Difficulty:  "Normal",
			Icon:        "droplets",
		},
		{
			ID:          "trial-chamber-ancient-city",
			Name:        "Trial Chamber Overlapping Ancient City",
			Seed:        "-109283746501",
			Category:    "1.21 Trials & Caves",
			Description: "The ultimate challenge dungeon: 1.21 Breeze spawners and copper trial vaults generated right above a sculk Warden sanctuary at deepslate level.",
			Biomes:      []string{"Trial Chambers", "Deep Dark", "Deepslate"},
			Features:    []string{"Breeze & Warden Collide", "Heavy Core Vaults", "Silence Armor Trim", "Epic Dual Dungeon"},
			Difficulty:  "Hardcore / Expert",
			Icon:        "zap",
		},
		{
			ID:          "jungle-crater-lake",
			Name:        "Jungle Caldera with Hidden Lagoon",
			Seed:        "7770192834",
			Category:    "Jungle Wilderness",
			Description: "A volcanic-style ring of lush jungle cliffs concealing a hidden central freshwater lagoon with wild pandas, parrots, and cocoa trees.",
			Biomes:      []string{"Jungle", "Bamboo Jungle", "River"},
			Features:    []string{"Ring of Jungle Cliffs", "Hidden Lagoon", "Wild Pandas", "Treehouse Canopy Setup"},
			Difficulty:  "Normal",
			Icon:        "trees",
		},
		{
			ID:          "triple-blacksmith-village",
			Name:        "Triple Blacksmith Coastal Village",
			Seed:        "1920394857102",
			Category:    "Villages & Exploration",
			Description: "A wealthy seaside settlement with three active blacksmith shops filled with iron armor, diamond pickaxes, obsidian, and iron ingots.",
			Biomes:      []string{"Plains", "Coastal Ocean", "Beach"},
			Features:    []string{"3x Blacksmith Houses", "Free Diamond & Iron Gear", "Safe Harbor", "Natural Docks"},
			Difficulty:  "Easy / Beginner",
			Icon:        "castle",
		},
		{
			ID:          "ice-spike-ring-valley",
			Name:        "Ice Spikes Ring Circling Frozen Meadow",
			Seed:        "-920192837465",
			Category:    "Winter Wonderland",
			Description: "A fortress-like ring of towering glacial ice spikes encasing a snowy meadow valley with polar bears, stray archers, and an igloo.",
			Biomes:      []string{"Ice Spikes", "Snowy Plains", "Frozen River"},
			Features:    []string{"Circular Ice Spike Ring", "Protected Glacial Basin", "Polar Bear Cubs", "Packed Ice Towers"},
			Difficulty:  "Normal",
			Icon:        "snowflake",
		},
		{
			ID:          "mega-caves-trial-network",
			Name:        "1.21 Trial Chambers with Triple Spider Spawners",
			Seed:        "8837192047",
			Category:    "1.21 Trials & Caves",
			Description: "An underground dungeon runner's dream: 1.21 Trial Chambers connected directly into multiple abandoned dungeon mob spawners for endless mob farming.",
			Biomes:      []string{"Trial Chambers", "Dungeons", "Lush Caves"},
			Features:    []string{"3x Connected Dungeon Spawners", "1.21 Breeze Trial Vaults", "Infinite XP Farm Potential", "Lush Cave Oasis"},
			Difficulty:  "Challenging",
			Icon:        "zap",
		},
	}
}
